import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

import BitwiseOperator from '../components/BitwiseOperator';
import BitwiseOperand from '../components/BitwiseOperand';

import { BitwiseOperator as EBitwiseOperator } from '../defs';

interface State {
  value1: number,
  value2: number,
  operatorIndex: number,
}

const calculateValue = (val1, val2, operatorIndex): number => {
  switch(OPERATORS[operatorIndex]) {
    case EBitwiseOperator.AND: return val1 & val2
    case EBitwiseOperator.OR: return val1 | val2
    case EBitwiseOperator.XOR: return val1 ^ val2
  }
}

const OPERATORS: EBitwiseOperator[] = [
  EBitwiseOperator.AND,
  EBitwiseOperator.XOR,
  EBitwiseOperator.OR
];

const Home: React.FC = () => {
  const [state, setState] = useState<State>({
    value1: 0xF6E5,
    value2: 0x4F4A,
    operatorIndex: 0,
  });

  const [operatorIndex, setOperatorIndex] = useState<number>(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BitwiseOperand value={state.value1} />

        <div className={styles.secondValue}>
          <BitwiseOperator onClickCallback={() => {
            if(operatorIndex + 1 == OPERATORS.length) {
              setOperatorIndex(() => 0);
            } else {
              setOperatorIndex((idx) => idx + 1);
            }
          }}  value={OPERATORS[operatorIndex]} />
          <BitwiseOperand value={state.value2} />
        </div>

        <BitwiseOperand value={calculateValue(state.value1, state.value2, operatorIndex)} />
      </main>
    </div>
  )
}

export default Home;
